sudo: required
dist: trusty

matrix:
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "8"

    - os: linux
      language: generic

cache:
  yarn: true
  directories:
    - node_modules

before_install:
- yarn install

script:
- yarn dist
